project:
  type: website
  output-dir: docs

website:
  title: "LS빅데이터 스쿨 포트폴리오"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    



