project:
  type: website
  output-dir: docs

website:
  title: "LS빅데이터 스쿨 포트폴리오"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: post/index.qmd
        

format:
  html:
    theme: cosmo
    toc: true
    



