---
title: ""
jupyter: python3
---

# 자기소개서

# 개인정보

| 항목         | 내용                     |
|--------------|--------------------------|
| 이름         | 박 한결                   |
| 영문         | Park HanGyeol             |
| 생년월일     | 970813                    |
| 휴대폰       | 010-2658-6918             |
| E-mail       | hg.park.970813@gmail.com  |
| 주소         | 서울 신당동 468           |

# 학력사항

| 재학기간        | 학교명 및 전공          | 학점        | 소재지   |
|-----------------|-------------------------|-------------|----------|
| 2016. 03 ~ 2020. 02 | 국립부경대학교 전자공학과 | 3.61 / 4.5  | 부산      |

# 경력사항 (전체경력: 1년 2개월)

| 근무기간           | 근무회사   | 부서 | 직위  | 담당직무   |
|--------------------|------------|------|-------|------------|
| 2022. 04 ~ 2023. 05 | ㈜다스코리아 | 연구소 | 매니저 | 기술지원   |

# 자격증

| 취득일자      | 자격증/면허증          | 발급처              | 자격 번호        |
|---------------|-------------------------|---------------------|------------------|
| 2023. 07. 07  | SQL 개발자(SQLD)        | 한국데이터산업진흥원 | SQLD-049010662   |
| 2023. 06. 16  | 데이터 분석 준전문가(ADsP) | 한국데이터산업진흥원 | ADsP-037008947   |
| 2021. 06. 02  | 전기공사기사            | 한국산업인력공단    | 21201170652W     |
| 2020. 12. 31  | 전기기사                | 한국산업인력공단    | 20204170287P     |
| 2020. 11. 06  | 컴퓨터활용능력 1급       | 대한상공회의소       | 20-K9-100085     |
| 2020. 8. 19   | 자동차 운전 면허 2종 보통 | 부산지방경찰청      | -                |

# 어학

| 기간           | 시험          | 점수  | 기관         |
|----------------|---------------|-------|--------------|
| 2021. 12. 19   | TOEIC         | 790점 | 한국TOEIC위원회 |
| 2022. 02. 26   | TOEIC Speaking | Intermediate Mid 3 | 한국TOEIC위원회 |
| 2023. 08. 18   | OPlc          | Intermediate Mid 2 | ACTFL          |

# 직무 관련 교육 사항

| 교육명                          | 기간                 | 기관               | 주요 내용                                                                                     |
|----------------------------------|----------------------|--------------------|------------------------------------------------------------------------------------------------|
| LS 빅데이터 스쿨 3기   | 2024.07.08 ~ 2024.11.08(교육 진행중) | LS             | 파이썬 프로그래밍, 데이터 수집 및 관리, 통계 분석, 데이터 시각화, 파이썬 머신러닝, 딥러닝, 시각화 대시보드 개발
| [백엔드] Python 첫걸음 시작하기   | 2024.01.02 ~ 2024.02.12 | TECHIT             | 변수와 자료형, 조건문/반복문, 리스트, 튜플, 딕셔너리, 객체지향 등 Python 기초 실습                          |
| [데이터분석] 실무에 필요한 데이터 분석&시각화 | 2024.01.02 ~ 2024.02.12 | TECHIT             | 데이터 분석 이론, 데이터 수집, 데이터 시각화, 데이터 분석 방법 실습                               |
| X-SCADA 기본과정                 | 2022.11.22 ~ 2022.11.23 | (주)자이솜           | X-SCADA를 활용한 HMI 설계 및 작화, 데이터 수집, 경보, 트렌드 보고서 출력, 카메라 연동 실습            |
| [기술]쉽게 배우는 MS-SQL SERVER기본 | 2022.09.21 ~ 2022.09.23 | 한국생산성본부       | MS-SQL을 이용하여 필요한 데이터를 추출하고 조작하는 방법 실습                                     |
| Java 프로그래밍                 | 2022.08.22 ~ 2022.08.26 | 한국생산성본부       | Java 개발환경 구축, 기본구조 이해, 객체지향 개념 이해 및 개발                                      |
| AutoCAD기초                     | 2022.07.25 ~ 2022.07.29 | 한국생산성본부       | AutoCAD를 활용한 도면 작성 및 수정                                                            |

# 활용가능 Tool

| 구분              | 활용가능 프로그램         | 내용                                      |
|-------------------|--------------------------|-------------------------------------------|
| HMI               | GP-Pro Ex                 | Proface의 HMI 작화 프로그램 사용         |
| PLC               | Machine Expert            | Schneider Electric의 PLC 로직 프로그램 |
| SCADA             | X-SCADA                   | 국내 소프트웨어 업체 Xisom의 SCADA 소프트웨어 |
| 통신 프로토콜     | Modbus, OPC-UA            | 다양한 하위 디바이스와 통신 가능한 산업용 프로토콜 |
| DBMS              | MS-SQL, Oracle DB         | 데이터베이스 관리 및 질의 언어 사용       |
| OA                | MS-PowerBI, MS-Reportbuilder | 데이터 시각화 및 보고서 작성 프로그램 |
| 공학용            | MATLAB, VHDL              | 통신 시스템 설계 및 FPGA 보드 입/출력 제어 |
| 언어              | Python                    | 데이터 전처리 및 시각화 강의 수강, Python을 활용한 데이터 분석 및 머신러닝 모델 예측 가능        |

# 기타활동

| 기간               | 활동 내용                                | 기관                        |
|--------------------|-------------------------------------------|-----------------------------|
| 2016.03 ~ 2017.12  | 학과 학생회 활동 - 학생 사물함 관리, 축제 행사 부스 운영 등 학과 행사 진행 | 국립부경대학교 전자공학과 학생회 |
| 2016.05.27 ~ 2016.05.29 | 대학생 농촌봉사활동 – 농어촌 봉사 일손지원        | 경상남도 합천군               |
| 2016.07.26 ~ 2016.08.29 | 재능기부 활동 - 초등학생 아동 미술 수업 진행         | 부산광역시 남구 엄마품에 지역아동센터 |

# 수행 프로젝트

| 회사명       | 부서        | 직급  |
|----------------|---------------|-------|
| (주)다스코리아 | 연구소        | 매니저| 


## 프로젝트명
NOBLAND 송파 본사 건물 전력 및 화재감지 모니터링 시스템

- 프로젝트 기간: 2022.10 ~ 2023.01
- 주요 역할 및 담당:
    - 전력 모니터링 시스템(PME) 화면 작화 및 대시보드 트렌드 알람 구성
    - 데이터 분석 역량 (SQL 및 리포트 생성) 인정받아 데이터베이스 관리 및 전력 소비량 계산 리포트 제공
    - 화재 감지 모니터링 데모 아키텍처 구성 및 X-SCADA 사용한 데모 시스템 구성
    - 분전반 내 디바이스 시운전 및 초기값 세팅 및 설치

업무 성과:
- 전력 모니터링 시스템 구상 및 PME 화면 작화
- MS-ReportBuilder 및 PowerBI 사용한 리포트 생성

## 프로젝트명
태림산업 창원 공장 전력 모니터링 시스템

- 프로젝트 기간: 2022. 05 ~ 2022. 08
- 주요 역할 및 담당:
    - 전력 모니터링 시스템(PME) 화면 작화 및 대시보드 트렌드 알람 구성